// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQguF0Q5rIaPaHuKU-9wH4Wm79NOOCmT8',
    appId: '1:410298852575:web:05fcec9e660cbdd533356a',
    messagingSenderId: '410298852575',
    projectId: 'hushstack-52ddd',
    authDomain: 'hushstack-52ddd.firebaseapp.com',
    storageBucket: 'hushstack-52ddd.firebasestorage.app',
    measurementId: 'G-88J7JHSEY1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYf_OnQ5NO2pwCxd7oo_ku18vZ3RHy9-g',
    appId: '1:410298852575:android:f4cb78a4cacbb51133356a',
    messagingSenderId: '410298852575',
    projectId: 'hushstack-52ddd',
    storageBucket: 'hushstack-52ddd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABq-bOPR21gnhsdwbZxfbMqI6O0bcLeqM',
    appId: '1:410298852575:ios:81100208d326dfc833356a',
    messagingSenderId: '410298852575',
    projectId: 'hushstack-52ddd',
    storageBucket: 'hushstack-52ddd.firebasestorage.app',
    iosBundleId: 'com.example.socialPlatformApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABq-bOPR21gnhsdwbZxfbMqI6O0bcLeqM',
    appId: '1:410298852575:ios:81100208d326dfc833356a',
    messagingSenderId: '410298852575',
    projectId: 'hushstack-52ddd',
    storageBucket: 'hushstack-52ddd.firebasestorage.app',
    iosBundleId: 'com.example.socialPlatformApp',
  );

}